name: Docker-Java

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
    schedule:
        - cron: '0 0 * * 1'
    push:
        branches:
            - main
        paths:
            - java/**
    workflow_dispatch:

env:
    REGISTRY: ghcr.io

jobs:
    push:
        name: 'pterodactyl-images:java-${{ matrix.tag }}'
        runs-on: ubuntu-latest
        strategy:
            matrix:
                tag:
                    - 8
                    - 11
                    - 15
                    - j9-11
                    - j9-15
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Log into registry ${{ env.REGISTRY }}
              uses: docker/login-action@v1
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                  context: ./java
                  file: ./java/${{ matrix.tag }}/Dockerfile
                  platforms: linux/amd64
                  push: true
                  tags: ghcr.io/hask-hosting/pterodactyl-images:java-${{ matrix.tag }}
